name: Daily Random Wikipedia Post

on:
  schedule:
    - cron: "0 14 * * *"   # every day at 2 PM UTC
  workflow_dispatch:        # allows manual runs

jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-fetch@3

      - name: Ensure articles.json exists
        run: |
          if [ ! -f articles.json ]; then
            echo "[]" > articles.json
          fi

      - name: Run the script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node dailyWiki.js

      - name: Commit updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add articles.json
          git commit -m "Update daily article" || echo "No changes"
          git push
